### ISSUE TITLE
Make it an official Gephi plugin

### ISSUE THREAD

**Issue by mbastian** [govertb/ReadabilityMetrics#1]
Hi folks, 

There has been some interest in this plugin on Twitter (see https://twitter.com/PhMai/status/1577728765635039260). To enhance diffusion and fix compatibility issue why not make it part of the official list of Gephi plugins? Thank you!

**Comment by govertb** [comment]
Hi!

Thanks for reaching out. As you may have noticed, @aabversteeg and I developed this plugin some years ago as part of a [university course](https://liacs.leidenuniv.nl/~takesfw/SNACS/index2015.html). Personally I haven't followed the Gephi developments since, and I currently don't have the spare time to incorporate it as an official plugin...

However, in the twitter thread I read that the lack of a license on this project currently blocks others from forking it and turning it into an official plugin. Is there a particular license that's commonly used for plugins? If so, I'd be happy to check with @aabversteeg and add it here. Thanks!

**Comment by mbastian** [comment]
Hi @govertb, the [Apache 2 License](https://www.apache.org/licenses/LICENSE-2.0) is commonly used. With that added, we could fork it and try to find a new maintainer. Thank you!

**Comment by aabversteeg** [comment]
Hi!
Sorry for the late reply. Great to see this initiative! I fully support it.
